#!/system/bin/sh
# OrangeFox HID Mouse wrapper
if ! /system/bin/hid-gadget mouse "$@"; then
    echo "HID Mouse failed, triggering auto-setup..."
    /system/bin/hid-setup
    exec /system/bin/hid-gadget mouse "$@"
fi
